language: rust
sudo: false
cache: cargo
rust:
- stable
- beta
- nightly
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt --vers 0.7.1
- rustfmt --version
script:
- cargo build --verbose
- cargo fmt --verbose -- --write-mode=diff
- cargo test --verbose -- --skip test2
- cargo test test2
- cargo run --example cmd-program
- cargo run --example cmd-program -- --verbose
