language: rust
sudo: false
cache: cargo
rust:
- 1.32.0
- stable
- beta
- nightly
os:
- linux
- osx
matrix:
  include:
  - os: linux
    rust: stable
    sudo: true
    addons:
      apt:
        packages:
        - libssl-dev
    script: | # cargo tarpaulin
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh) &&
      cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  allow_failures:
    - script: | # cargo tarpaulin
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh) &&
        cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
script:
- cargo test --verbose
- cargo test --verbose --features=colored
- cargo test --verbose --features=syslog-3
- cargo test --verbose --features=syslog-5
- cargo test --verbose --features=reopen-03
- cargo test --verbose --features=meta-logging-in-format
- cargo test --verbose --all-features
- cargo run --example cmd-program
- cargo run --example cmd-program -- --verbose
- cargo run --example colored --features colored
- cargo run --example pretty-colored --features colored
- cargo run --example syslog --features syslog-5
- cargo run --example syslog3 --features syslog-3
- cargo run --example date-based-file-log --features date-based
  # we don't exactly have a good test suite for DateBased right now, so let's at least do this:
- cargo run --example date-based-file-log --features date-based,meta-logging-in-format
