# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

environment:
    matrix:
    # Stable
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: stable
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: stable
    - TARGET: i686-pc-windows-gnu
      RUST_VERSION: stable
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: stable

    # Beta
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: beta
    - TARGET: i686-pc-windows-gnu
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: beta

    # Nightly
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly
    - TARGET: i686-pc-windows-gnu
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: nightly

matrix:
    fast_finish: true
    allow_failures:
    - RUST_VERSION: nightly

install:
- curl -sSf -o rustup-init.exe https://win.rustup.rs/
- rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
- set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
- rustc -Vv
- cargo -V

test_script:
- cargo test --verbose
- cargo test --verbose --features=colored
- cargo test --verbose --features=meta-logging-in-format
- cargo test --verbose --all-features
- cargo run --example cmd-program
- cargo run --example cmd-program -- --verbose
- cargo run --example colored --features colored

cache:
- target

# Disable the appveyor build step so we can just build the rust project instead.
build: off
